"""The per-site representation must reproduce the stacked implementation exactly.

Fixtures (`stacked_fixtures.npz`) were generated by `gen_stacked_fixtures.py` running
against the pre-restructure `feature/jax-single-pool-pd` code (stacked `DecompVU`,
contiguous-MLP-only `llama_decomposed_lm`). This test rebuilds the identical model in
the per-site representation and checks, for the same MLP-family site set:

  * `clean_output` / per-site INPUTS (served by `lm.read_activations` for site-name keys) /
    `weight_deltas` / `masked_output` — to a portable fp32 reassociation tolerance (SPEC D4),
    not bit-exact: float32 matmul reduction order differs across CPU microarchitectures, so
    the same op sequence diverges by ~1 ULP between the fixture-generating host and a given
    CI runner (`ubuntu-latest` is a heterogeneous pool). These pins are CI-fn-INDEPENDENT —
    pure target-model forwards — so they still hold against the committed fixtures.

The trajectory test (`test_train_trajectory_matches`) is SKIPPED: the CI fn moved from the
old per-site-concat `CIArch` to the chunkwise transformer reading RESIDUAL taps, which
changes the CI numerics, so the CI-dependent goldens (`ci_leaf::*`, `out::step*`,
`out::final_{V,U,src}`) are stale and need a torch-oracle golden regen (the `torch-oracle`
git tag in a torch venv), out of scope for the API migration.
"""

from pathlib import Path

import equinox as eqx
import jax.numpy as jnp
import numpy as np
import optax
import pytest
from jax import random

from param_decomp.adversary import (
    PersistentAdversary,
    init_persistent_sources,
    init_sources_adam_state,
)
from param_decomp.components import DecompVU
from param_decomp.configs import (
    AdamPGDConfig,
    ChunkwiseSubsetReconLossConfig,
    FaithfulnessLossConfig,
    FrequencyMinimalityConfig,
    ImportanceMinimalityLossConfig,
    PersistentPGDReconLossConfig,
    SCScope,
    UniformKSubsetRoutingConfig,
)
from param_decomp.lm import DecomposedModel
from param_decomp.recon import StochasticSources, build_loss_terms, subset_chunk_plan
from param_decomp.schedule import ScheduleConfig
from param_decomp.targets.llama8b import (
    FrozenAttn,
    LlamaLayer,
    build_decomposed_lm,
    llama_site_specs,
    mlp_family_site_cs,
)
from param_decomp.tests.test_llama8b import _tiny_cfg
from param_decomp.train import TrainState, make_train_step
from vendored_jax.llama import llama3_inv_freq

FIXTURES = Path(__file__).resolve().parent / "stacked_fixtures.npz"
RTOL = 1e-4
ATOL = 1e-5

STABLE_FIXTURE_METRIC_KEYS = (
    "total", "faith", "imp", "stoch", "ppgd", "p_imp", "src_lr",
    "grad_norms/summary/components", "grad_norms/summary/ci_fns", "grad_norms/summary/total",
)  # fmt: skip
METRIC_KEY_BY_FIXTURE_KEY = {
    "stoch": "loss/ChunkwiseSubsetReconLoss",
    "ppgd": "loss/PersistentPGDReconLoss",
}
"""The fixtures predate the recon-loss-terms unification; their metric keys are the
old fixed names. The stored arrays themselves are untouched — only the lookup into
the live metrics dict is remapped."""


def _load() -> tuple[dict[str, np.ndarray], DecomposedModel, DecompVU, jnp.ndarray]:
    """Rebuild the fixtures' target as an embed-internal FULL model and return the token ids
    whose embedding reproduces the fixtures' residual entering layer `first`.

    The fixtures' goldens were pinned by a residual-fed suffix (absolute layers `first`..end,
    the residual injected at `first`). The current model takes token ids, embeds them, and
    scans ALL layers, and its site names carry absolute layer indices. So the model is the
    full `cfg.n_layer` stack: layers `< first` are identity (zeroed attn + zeroed MLP →
    `block(x) == x`), layers `>= first` are the stored frozen weights. `embed[tokens]` is set
    to the fixtures' residual (one distinct token per position, its embed row that position's
    residual — a pure gather, no arithmetic) and passes through the identity prefix unchanged,
    so layer `first` sees the identical residual and every CI-independent golden holds."""
    assert FIXTURES.exists(), "regenerate via gen_stacked_fixtures.py on the base branch"
    f = dict(np.load(FIXTURES))
    cfg = _tiny_cfg()
    first = int(f["_scalar_FIRST_LAYER"])
    last = int(f["_scalar_LAST_LAYER"])
    C = int(f["_scalar_C"])
    d, di = cfg.n_embd, cfg.n_intermediate
    qd, kvd = cfg.n_head * cfg.head_dim, cfg.n_kv_head * cfg.head_dim

    def a(key: str) -> jnp.ndarray:
        return jnp.asarray(f[key])

    def z(r: int, c: int) -> jnp.ndarray:
        return jnp.zeros((r, c), jnp.float32)

    def identity_layer() -> LlamaLayer:
        return LlamaLayer(
            ln1=jnp.ones((d,)), ln2=jnp.ones((d,)),
            attn=FrozenAttn(z(qd, d), z(kvd, d), z(kvd, d), z(d, qd),
                            cfg.n_head, cfg.n_kv_head, cfg.head_dim, cfg.n_rep),
            Wg=z(di, d), Wu=z(di, d), Wd=z(d, di),
        )  # fmt: skip

    def stored_layer(i: int) -> LlamaLayer:
        return LlamaLayer(
            ln1=a(f"tgt::layers.{i}.ln1"), ln2=a(f"tgt::layers.{i}.ln2"),
            attn=FrozenAttn(
                a(f"tgt::layers.{i}.wq"), a(f"tgt::layers.{i}.wk"),
                a(f"tgt::layers.{i}.wv"), a(f"tgt::layers.{i}.wo"),
                cfg.n_head, cfg.n_kv_head, cfg.head_dim, cfg.n_rep,
            ),
            Wg=a(f"tgt::layers.{i}.Wg"), Wu=a(f"tgt::layers.{i}.Wu"), Wd=a(f"tgt::layers.{i}.Wd"),
        )  # fmt: skip

    layers = [identity_layer() if i < first else stored_layer(i) for i in range(cfg.n_layer)]
    sites = llama_site_specs(cfg, mlp_family_site_cs(first, last, C))

    resid = np.asarray(f["resid"])
    B, T = resid.shape[:2]
    n_positions = B * T
    assert n_positions <= cfg.vocab_size, (n_positions, cfg.vocab_size)
    tokens = jnp.asarray(np.arange(n_positions, dtype=np.int32).reshape(B, T))
    embed = np.zeros((cfg.vocab_size, d), np.float32)
    embed[:n_positions] = resid.reshape(n_positions, d)

    lm = build_decomposed_lm(
        embed=jnp.asarray(embed),
        layers=layers, norm=a("tgt::norm"), lm_head=a("tgt::lm_head"),
        inv_freq=llama3_inv_freq(cfg), cfg=cfg, sites=sites,
    )  # fmt: skip
    vu = DecompVU(vu={s.name: (a(f"vu::V::{s.name}"), a(f"vu::U::{s.name}")) for s in sites})
    return f, lm, vu, tokens


def _assert_close(got: jnp.ndarray, want: np.ndarray, what: str) -> None:
    np.testing.assert_allclose(np.asarray(got), want, rtol=RTOL, atol=ATOL, err_msg=what)


def _build_trajectory_ci_fn(lm: DecomposedModel, key: jnp.ndarray):
    """The new chunkwise CI fn (one chunk over all sites, reading the residual entering the
    first decomposed block) — the migrated replacement for the old per-site `CIArch`."""
    from param_decomp.ci_fn import Chunk, ChunkwiseTransformerCIArch, build_ci_fn

    first_block = min(int(n.split(".")[1]) for n in lm.site_names)
    arch = ChunkwiseTransformerCIArch(
        chunks=(Chunk(input_taps=(f"resid.{first_block}",), output_sites=lm.site_names),),
        input_dim=_tiny_cfg().n_embd,
        d_model=16,
        n_blocks=2,
        n_heads=2,
        mlp_hidden=32,
    )
    return build_ci_fn(arch, lm.sites, key)


def test_clean_output_matches():
    f, lm, _vu, tokens = _load()
    clean = lm.clean_output(tokens)
    _assert_close(clean, f["out::clean"], "clean logits")


def test_site_inputs_and_weight_deltas_match():
    f, lm, vu, tokens = _load()
    site_inputs = lm.read_activations(tokens, lm.site_names)
    for name in lm.site_names:
        _assert_close(site_inputs[name], f[f"out::site_input::{name}"], f"site_input {name}")
    deltas = lm.weight_deltas(vu)
    for name in lm.site_names:
        _assert_close(deltas[name], f[f"out::wd::{name}"], f"weight_delta {name}")


def test_masked_output_match():
    f, lm, vu, tokens = _load()
    prepared = lm.prepare_compute_weights(vu)
    masks = {s: jnp.asarray(f[f"mask::{s}"]) for s in lm.site_names}
    delta_masks = {s: jnp.asarray(f[f"delta_mask::{s}"]) for s in lm.site_names}
    masked_all = lm.masked_output(
        prepared, tokens, masks, delta_masks, None, lm.site_names, True, remat=False
    )
    _assert_close(masked_all, f["out::masked_all"], "masked_output (all live)")

    chunk0 = lm.site_names[:3]
    routes0 = {s: jnp.asarray(f[f"route0::{s}"]) for s in chunk0}
    masked_subset = lm.masked_output(
        prepared, tokens,
        {s: masks[s] for s in chunk0}, {s: delta_masks[s] for s in chunk0}, routes0, chunk0, True,
        remat=False,
    )  # fmt: skip
    _assert_close(masked_subset, f["out::masked_subset"], "masked_output (subset live)")


def test_chunk_plan_static_live_set_matches():
    """The production `subset_chunk_plan` (`ChunkwiseSubsetReconLoss`) is what reaches the
    static live-set realization of SPEC S2: each plan entry holds a STATIC `live_sites`
    tuple, and `masked_output` runs every absent site on the frozen `x @ W` path (no
    `(B,T,C)` acts) — distinct from the per-position routing fallback. This drives that
    plan directly and asserts its first chunk's frozen-site forward matches the torch
    golden (`out::masked_subset`), so the chunk-plan path is verified against the oracle.
    """
    f, lm, vu, tokens = _load()

    plan = subset_chunk_plan(
        lm.site_names, sites_per_chunk=3, n_samples=1, sources=StochasticSources()
    )
    chunk0 = lm.site_names[:3]
    assert plan[0].live_sites == chunk0, (plan[0].live_sites, chunk0)
    assert all(len(entry.live_sites) == 3 for entry in plan), [e.live_sites for e in plan]

    masks = {s: jnp.asarray(f[f"mask::{s}"]) for s in chunk0}
    delta_masks = {s: jnp.asarray(f[f"delta_mask::{s}"]) for s in chunk0}
    routes = {s: jnp.asarray(f[f"route0::{s}"]) for s in chunk0}
    masked = lm.masked_output(
        lm.prepare_compute_weights(vu), tokens, masks, delta_masks, routes,
        plan[0].live_sites, plan[0].has_delta, remat=False,
    )  # fmt: skip
    _assert_close(masked, f["out::masked_subset"], "chunk-plan static-live-set forward")


@pytest.mark.xfail(
    reason="needs torch-oracle golden regen: CI numerics changed. The CI fn moved from the "
    "old per-site-concat `CIArch` to the chunkwise transformer reading RESIDUAL taps "
    "(`ChunkwiseTransformerCIFn`), so every CI-dependent trajectory golden (`out::step*`, "
    "`out::final_{V,U,src}`) is stale. Regen is torch-oracle-dependent (the `torch-oracle` "
    "git tag in a torch venv), out of scope for the API migration. The CI-INDEPENDENT "
    "forward pins (clean / site_input / weight_delta / masked) still verify in the other "
    "tests. The body below is migrated to the new chunkwise CI fn so it runs (and fails on "
    "the stale numerics) rather than erroring.",
    strict=True,
)
def test_train_trajectory_matches():
    f, lm, vu, tokens = _load()
    T = int(f["_scalar_T"])
    n_train_steps = int(f["_scalar_N_TRAIN_STEPS"])
    n_warmup = int(f["_scalar_N_WARMUP"])

    ci_fn = _build_trajectory_ci_fn(lm, random.PRNGKey(2))
    sources = init_persistent_sources(
        lm.site_names, tuple(s.C for s in lm.sites), (1, T), jnp.float32, random.PRNGKey(3)
    )
    for name, source in sources.items():
        np.testing.assert_array_equal(np.asarray(source), f[f"src::{name}"])

    opt_vu = optax.chain(optax.clip_by_global_norm(0.01), optax.adamw(1e-3, weight_decay=0.0))
    opt_ci = optax.adamw(1e-3, weight_decay=0.0)
    ppgd_cfg = PersistentPGDReconLossConfig(
        coeff=0.5,
        scope=SCScope(),
        optimizer=AdamPGDConfig(
            beta1=0.5,
            beta2=0.99,
            lr_schedule=ScheduleConfig(start_val=0.01, warmup_pct=0.025),
        ),
        n_warmup_steps=n_warmup,
    )
    assert ppgd_cfg.coeff is not None
    state = TrainState(
        components=vu, ci_fn=ci_fn,
        components_opt_state=opt_vu.init(eqx.filter(vu, eqx.is_array)),
        ci_fn_opt_state=opt_ci.init(eqx.filter(ci_fn, eqx.is_array)),
        adversaries={
            ppgd_cfg.type: PersistentAdversary(
                sources=sources,
                opt_state=init_sources_adam_state(sources),
                state_key=ppgd_cfg.type,
                coeff=ppgd_cfg.coeff,
                adam=ppgd_cfg.optimizer,
                n_warmup=ppgd_cfg.n_warmup_steps,
            )
        },
        step=jnp.zeros((), jnp.int32),
    )  # fmt: skip
    loss_terms = build_loss_terms(
        (
            FaithfulnessLossConfig(coeff=1e5),
            ImportanceMinimalityLossConfig(
                coeff=5e-6,
                pnorm=2.0,
                frequency=FrequencyMinimalityConfig(coeff=1e-6, reference_token_count=32),
                p_anneal_start_frac=0.0,
                p_anneal_final_p=0.4,
                p_anneal_end_frac=1.0,
            ),
            ChunkwiseSubsetReconLossConfig(
                routing=UniformKSubsetRoutingConfig(), coeff=0.5, sites_per_chunk=3, n_samples=1
            ),
            ppgd_cfg,
        ),
        lm.site_names,
    )
    step_fn = make_train_step(
        lm=lm,
        losses=loss_terms,
        components_optimizer=opt_vu,
        ci_fn_optimizer=opt_ci,
        total_steps=100,
        remat_recon_forwards=False,
        remat_ci_fn=False,
        mesh=None,
    )
    run_key = random.PRNGKey(7)
    for step_idx in range(n_train_steps):
        state, metrics = step_fn(lm, state, tokens, random.fold_in(run_key, step_idx))
        for fixture_key in STABLE_FIXTURE_METRIC_KEYS:
            metric_key = METRIC_KEY_BY_FIXTURE_KEY.get(fixture_key, fixture_key)
            got = float(metrics[metric_key])
            want = float(f[f"out::step{step_idx}::{fixture_key}"])
            assert abs(got - want) <= ATOL + RTOL * abs(want), (
                f"step{step_idx} {fixture_key}: per-site {got!r} vs stacked {want!r}"
            )

    assert isinstance(state.components, DecompVU)
    for name in lm.site_names:
        V, U = state.components.site(name)
        _assert_close(V, f[f"out::final_V::{name}"], f"final V {name}")
        _assert_close(U, f[f"out::final_U::{name}"], f"final U {name}")
    final_sources = state.adversaries["PersistentPGDReconLoss"].sources
    for name in lm.site_names:
        _assert_close(final_sources[name], f[f"out::final_src::{name}"], f"final src {name}")
