current_model_path: "wandb:goodfire/spd/runs/s-e8bde534"
reference_model_path: "wandb:goodfire/spd/runs/s-73d2385c"

mean_ci_threshold: 1e-5
n_eval_steps: 50

eval_batch_size: 128
shuffle_data: false
