"""The per-site representation must reproduce the stacked implementation exactly.

Fixtures (`stacked_fixtures.npz`) were generated by `gen_stacked_fixtures.py` running
against the pre-restructure `feature/jax-single-pool-pd` code (stacked `DecompVU`,
contiguous-MLP-only `llama_decomposed_lm`). This test rebuilds the identical model in
the per-site representation and checks, for the same MLP-family site set:

  * `clean_logits` — BIT-identical (same op sequence on the frozen path).
  * `site_inputs` / `weight_deltas` / `masked_logits` — to fp32 reassociation
    tolerance (SPEC D4: rel ~1e-5; observed essentially exact).
  * a 2-step training trajectory (metrics + final V/U + final adversary sources) —
    rel ~1e-5. The sources / train-step code is unchanged, so their RNG streams
    reproduce; the V/U init RNG derivation changed with the layout, so initial V/U
    load from the fixture.

The forward-pin arrays (clean / site-input / weight-delta / masked) still pin the
original stacked torch oracle. The trajectory `out::` arrays were re-baselined from
current HEAD after the CI-fn forward was aligned to the torch oracle (exact-erf GELU
#624, finfo(fp32) RMS eps #625): those numerics perturb the CI outputs, so `imp` and
the CI-fn grad norms compound away from the pre-fix golden by step 1. The trajectory
now pins the torch-faithful baseline, not the pre-#624/#625 one.
"""

from pathlib import Path

import equinox as eqx
import jax
import jax.numpy as jnp
import numpy as np
import optax
from jax import random

from jax_single_pool.adversary import init_persistent_sources, init_sources_adam_state
from jax_single_pool.ci_fn import CIArch, init_ci_fn
from jax_single_pool.llama8b import (
    DecompVU,
    FrozenAttn,
    SuffixLayer,
    Target,
    llama3_inv_freq,
    llama_decomposed_lm,
    llama_site_specs,
    mlp_family_site_cs,
)
from jax_single_pool.lm import DecomposedLM
from jax_single_pool.recon import StochasticSources, build_recon_terms, subset_chunk_plan
from jax_single_pool.tests.test_llama8b import _tiny_cfg
from jax_single_pool.train import TrainState, make_train_step
from param_decomp_config.losses import (
    AdamPGDConfig,
    ChunkwiseSubsetReconLossConfig,
    FaithfulnessLossConfig,
    ImportanceMinimalityLossConfig,
    PersistentPGDReconLossConfig,
    SCScope,
)
from param_decomp_config.routing import UniformKSubsetRoutingConfig
from param_decomp_config.schedule import ScheduleConfig

FIXTURES = Path(__file__).resolve().parent / "stacked_fixtures.npz"
RTOL = 1e-5
ATOL = 1e-6
CI_ARCH = CIArch(d_model=16, n_blocks=2, n_heads=2, mlp_hidden=32)
STABLE_FIXTURE_METRIC_KEYS = (
    "total", "faith", "imp", "stoch", "ppgd", "p_imp", "src_lr",
    "grad_norms/summary/components", "grad_norms/summary/ci_fns", "grad_norms/summary/total",
)  # fmt: skip
METRIC_KEY_BY_FIXTURE_KEY = {
    "stoch": "loss/ChunkwiseSubsetReconLoss",
    "ppgd": "loss/PersistentPGDReconLoss",
}
"""The fixtures predate the recon-loss-terms unification; their metric keys are the
old fixed names. The stored arrays themselves are untouched — only the lookup into
the live metrics dict is remapped."""


def _load() -> tuple[dict[str, np.ndarray], DecomposedLM, Target, DecompVU, jnp.ndarray]:
    assert FIXTURES.exists(), "regenerate via gen_stacked_fixtures.py on the base branch"
    f = dict(np.load(FIXTURES))
    cfg = _tiny_cfg()
    first = int(f["_scalar_FIRST_LAYER"])
    last = int(f["_scalar_LAST_LAYER"])
    C = int(f["_scalar_C"])

    def a(key: str) -> jnp.ndarray:
        return jnp.asarray(f[key])

    layers = [
        SuffixLayer(
            ln1=a(f"tgt::layers.{i}.ln1"),
            ln2=a(f"tgt::layers.{i}.ln2"),
            attn=FrozenAttn(
                a(f"tgt::layers.{i}.wq"),
                a(f"tgt::layers.{i}.wk"),
                a(f"tgt::layers.{i}.wv"),
                a(f"tgt::layers.{i}.wo"),
                cfg.n_head,
                cfg.n_kv_head,
                cfg.head_dim,
                cfg.n_rep,
            ),  # fmt: skip
            Wg=a(f"tgt::layers.{i}.Wg"),
            Wu=a(f"tgt::layers.{i}.Wu"),
            Wd=a(f"tgt::layers.{i}.Wd"),
        )
        for i in range(first, cfg.n_layer)
    ]
    tgt = Target(
        layers=layers, norm=a("tgt::norm"), lm_head=a("tgt::lm_head"),
        inv_freq=llama3_inv_freq(cfg), eps=cfg.rms_norm_eps,
    )  # fmt: skip
    sites = llama_site_specs(cfg, mlp_family_site_cs(first, last, C))
    lm = llama_decomposed_lm(cfg, sites)
    vu = DecompVU(vu={s.name: (a(f"vu::V::{s.name}"), a(f"vu::U::{s.name}")) for s in sites})
    return f, lm, tgt, vu, a("resid")


def _assert_close(got: jnp.ndarray, want: np.ndarray, what: str) -> None:
    np.testing.assert_allclose(np.asarray(got), want, rtol=RTOL, atol=ATOL, err_msg=what)


def test_clean_logits_bit_identical():
    f, lm, tgt, _vu, resid = _load()
    clean = lm.clean_logits(tgt, resid)
    assert jnp.array_equal(clean, jnp.asarray(f["out::clean"])), (
        "clean logits diverged from the stacked implementation (must be bit-identical)"
    )


def test_site_inputs_and_weight_deltas_match():
    f, lm, tgt, vu, resid = _load()
    site_inputs = lm.site_inputs(tgt, resid)
    for name in lm.site_names:
        _assert_close(site_inputs[name], f[f"out::site_input::{name}"], f"site_input {name}")
    deltas = lm.weight_deltas(tgt, vu)
    for name in lm.site_names:
        _assert_close(deltas[name], f[f"out::wd::{name}"], f"weight_delta {name}")


def test_masked_logits_match():
    f, lm, tgt, vu, resid = _load()
    masks = {s: jnp.asarray(f[f"mask::{s}"]) for s in lm.site_names}
    delta_masks = {s: jnp.asarray(f[f"delta_mask::{s}"]) for s in lm.site_names}
    masked_all = lm.masked_logits(tgt, vu, resid, masks, delta_masks, None, lm.site_names, True)
    _assert_close(masked_all, f["out::masked_all"], "masked_logits (all live)")

    chunk0 = lm.site_names[:3]
    routes0 = {s: jnp.asarray(f[f"route0::{s}"]) for s in chunk0}
    masked_subset = lm.masked_logits(
        tgt, vu, resid,
        {s: masks[s] for s in chunk0}, {s: delta_masks[s] for s in chunk0}, routes0, chunk0, True,
    )  # fmt: skip
    _assert_close(masked_subset, f["out::masked_subset"], "masked_logits (subset live)")


def test_chunk_plan_static_live_set_matches():
    """The production `subset_chunk_plan` (`ChunkwiseSubsetReconLoss`) is what reaches the
    static live-set realization of SPEC S2: each plan entry holds a STATIC `live_sites`
    tuple, and `masked_logits` runs every absent site on the frozen `x @ W` path (no
    `(B,T,C)` acts) — distinct from the per-position routing fallback. This drives that
    plan directly and asserts its first chunk's frozen-site forward matches the torch
    golden (`out::masked_subset`), so the chunk-plan path is verified against the oracle.
    """
    f, lm, tgt, vu, resid = _load()

    plan = subset_chunk_plan(
        lm.site_names, sites_per_chunk=3, n_samples=1, sources=StochasticSources("continuous")
    )
    chunk0 = lm.site_names[:3]
    assert plan[0].live_sites == chunk0, (plan[0].live_sites, chunk0)
    assert all(len(entry.live_sites) == 3 for entry in plan), [e.live_sites for e in plan]

    masks = {s: jnp.asarray(f[f"mask::{s}"]) for s in chunk0}
    delta_masks = {s: jnp.asarray(f[f"delta_mask::{s}"]) for s in chunk0}
    routes = {s: jnp.asarray(f[f"route0::{s}"]) for s in chunk0}
    masked = lm.masked_logits(
        tgt, vu, resid, masks, delta_masks, routes, plan[0].live_sites, plan[0].has_delta
    )
    _assert_close(masked, f["out::masked_subset"], "chunk-plan static-live-set forward")


def test_train_trajectory_matches():
    f, lm, tgt, vu, resid = _load()
    T = int(f["_scalar_T"])
    n_train_steps = int(f["_scalar_N_TRAIN_STEPS"])
    n_warmup = int(f["_scalar_N_WARMUP"])

    # ci_fn / sources init code is unchanged — same keys must reproduce the fixture's
    # values leaf-for-leaf (guards against silent init drift invalidating the parity).
    ci_fn = init_ci_fn(CI_ARCH, lm.sites, random.PRNGKey(2))
    for leaf_idx, leaf in enumerate(jax.tree.leaves(eqx.filter(ci_fn, eqx.is_array))):
        np.testing.assert_array_equal(np.asarray(leaf), f[f"ci_leaf::{leaf_idx}"])
    sources = init_persistent_sources(
        lm.site_names, tuple(s.C for s in lm.sites), T, random.PRNGKey(3)
    )
    for name, source in sources.items():
        np.testing.assert_array_equal(np.asarray(source), f[f"src::{name}"])

    opt_vu = optax.chain(optax.clip_by_global_norm(0.01), optax.adamw(1e-3, weight_decay=0.0))
    opt_ci = optax.adamw(1e-3, weight_decay=0.0)
    state = TrainState(
        components=vu, ci_fn=ci_fn,
        components_opt_state=opt_vu.init(eqx.filter(vu, eqx.is_array)),
        ci_fn_opt_state=opt_ci.init(eqx.filter(ci_fn, eqx.is_array)),
        sources={"PersistentPGDReconLoss": sources},
        sources_opt_state={"PersistentPGDReconLoss": init_sources_adam_state(sources)},
        step=jnp.zeros((), jnp.int32),
    )  # fmt: skip
    loss_spec = build_recon_terms(
        (
            FaithfulnessLossConfig(coeff=1e5),
            ImportanceMinimalityLossConfig(
                coeff=5e-6,
                pnorm=2.0,
                beta=0.2,
                p_anneal_start_frac=0.0,
                p_anneal_final_p=0.4,
                p_anneal_end_frac=1.0,
            ),
            ChunkwiseSubsetReconLossConfig(
                routing=UniformKSubsetRoutingConfig(), coeff=0.5, sites_per_chunk=3, n_samples=1
            ),
            PersistentPGDReconLossConfig(
                coeff=0.5,
                scope=SCScope(),
                optimizer=AdamPGDConfig(
                    beta1=0.5,
                    beta2=0.99,
                    lr_schedule=ScheduleConfig(start_val=0.01, warmup_pct=0.025),
                ),
                n_warmup_steps=n_warmup,
            ),
        ),
        lm.site_names,
        n_mask_samples=1,
        sampling="continuous",
    )
    step_fn = make_train_step(
        lm=lm,
        loss_spec=loss_spec,
        components_optimizer=opt_vu,
        ci_fn_optimizer=opt_ci,
        total_steps=100,
        remat_recon_forwards=False,
        mesh=None,
    )
    run_key = random.PRNGKey(7)
    for step_idx in range(n_train_steps):
        state, metrics = step_fn(state, tgt, resid, random.fold_in(run_key, step_idx))
        for fixture_key in STABLE_FIXTURE_METRIC_KEYS:
            metric_key = METRIC_KEY_BY_FIXTURE_KEY.get(fixture_key, fixture_key)
            got = float(metrics[metric_key])
            want = float(f[f"out::step{step_idx}::{fixture_key}"])
            assert abs(got - want) <= ATOL + RTOL * abs(want), (
                f"step{step_idx} {fixture_key}: per-site {got!r} vs stacked {want!r}"
            )

    assert isinstance(state.components, DecompVU)
    for name in lm.site_names:
        V, U = state.components.site(name)
        _assert_close(V, f[f"out::final_V::{name}"], f"final V {name}")
        _assert_close(U, f[f"out::final_U::{name}"], f"final U {name}")
    final_sources = state.sources["PersistentPGDReconLoss"]
    for name in lm.site_names:
        _assert_close(final_sources[name], f[f"out::final_src::{name}"], f"final src {name}")
