"""The trainer's built-run bundle — the pydantic algorithm config (`PDConfig` /
`RuntimeConfig` / `Cadence`) plus the objects a composition root resolves/builds before
entering the generic engine (`run.py::run_decomposition_training`).

The engine reads `pd` / `cadence` / `runtime` DIRECTLY (no flattened mirror): optimizers,
faith warmup, loss metrics, seed, steps all come off `PDConfig`. The bundle only
carries the things that are genuinely BUILT lab-side and cannot live in the pydantic schema:
the run identity (`RunInstance`), the decomposed `target` (typed by the `TargetSites`
protocol — just `.sites`), the resolved `data` source (`DataConfig | None`, None for a
positionless toy), the built CI-fn architecture (`CIFnArch`), and the resolved scalar-tier
`EvalConfig`. The YAML→bundle CONVERSION is COMPOSITION and lives lab-side
(`param_decomp_lab/experiments/`).
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Literal, Protocol

from param_decomp.ci_fn import CIFnArch
from param_decomp.components import SiteC
from param_decomp.configs import Cadence, PDConfig, ResumeProvenance, RuntimeConfig, WandbConfig

LAUNCH_CONFIG_FILENAME = "launch_config.yaml"
"""The self-contained run config pinned into each run dir. Not `config.yaml` — that basename
clashes with wandb's own run-config file, which `wandb.save` would clobber via symlink."""


class TargetSites(Protocol):
    """The only thing the generic engine needs from a target config: its decomposed
    sites. LM target configs live lab-side; non-LM targets (the toys) live in the lab
    and supply their own config dataclass — the core never names them."""

    @property
    def sites(self) -> tuple[SiteC, ...]: ...


WeightsDtype = Literal["float32", "bfloat16"]


@dataclass(frozen=True)
class DataConfig:
    """The LM pre-tokenized parquet data source. `None` on `BuiltRun` for a non-LM (toy)
    run, whose synthetic data is generated by its lab `sample_batch`."""

    dir: Path
    seq_len: int
    global_batch: int


@dataclass(frozen=True)
class EvalPGDConfig:
    """Fresh sign-PGD recon probe (torch eval `PGDReconLoss`: init random, source
    shared across batch and positions)."""

    n_steps: int
    step_size: float


@dataclass(frozen=True)
class AttnPatternsEvalConfig:
    """In-loop attention-pattern recon metrics (torch `CIMaskedAttnPatternsReconLoss` /
    `StochasticAttnPatternsReconLoss`). Q/K are read from the decomposed `*q_proj`/`*k_proj`
    sites; the attention recipe (RoPE/GQA/head-dim) is read from the target — so no
    config-side n_heads/paths are threaded here. The flags select which variants run."""

    ci_masked: bool
    stochastic: bool
    stochastic_n_mask_samples: int
    """Stochastic-variant mask-sample count (from `StochasticAttnPatternsReconLossConfig`);
    moot when `stochastic` is False."""


@dataclass(frozen=True)
class EvalConfig:
    """In-loop eval pass (torch `EvalLoop` analog). The FAST scalar tier runs every
    `every` steps; the SLOW/plot tier (CI histograms, activation density, mean-CI,
    hidden-acts recon) runs every `slow_every` steps, reusing the same eval batches
    (SPEC S28/S29). `rounding_threshold` binarises CI for the CE/KL `rounded_masked`
    variant; the CI-L0 metric and the activation-density step each carry their own aliveness
    cutoff (`l0_ci_alive_threshold` / `density_ci_alive_threshold`)."""

    batch_size: int
    every: int
    n_steps: int
    slow_every: int
    """The slow/plot tier cadence — a multiple of `every` (torch `EvalLoop.slow_every`),
    so the slow tier lands on a fast-eval step and reuses its eval batches."""
    slow_on_first_step: bool
    """Render the slow tier at the FIRST eval step too (torch parity), not only at
    `slow_every` multiples."""
    slow_n_batches_accum: int | None
    """The torch `CIHistograms.n_batches_accum` cap on the histogram raw-value sample
    (None caps nothing). Read from the `CIHistograms` eval metric when present."""
    density_heatmap_n_bins: int | None
    """`CIHistograms.density_heatmap_n_bins`: opt into the per-token CI density heatmap with
    this many log-spaced `[1e-9, 1]` bands (None = off). Shares the slow-eval forward."""
    rounding_threshold: float
    l0_ci_alive_threshold: float
    """CI aliveness cutoff for the CI-L0 metric (fast pass), from `CI_L0Config`."""
    density_ci_alive_threshold: float
    """CI aliveness cutoff for the activation-density slow-eval step, from
    `ComponentActivationDensityConfig` — independent of the CI-L0 cutoff (each metric owns
    its own, as on the torch oracle)."""
    l0_groups: dict[str, tuple[str, ...]] | None
    """torch CI_L0 `groups`: fnmatch site patterns whose member L0s sum into a
    group-named key. None = per-site keys only."""
    pgd: EvalPGDConfig | None
    attn_patterns: AttnPatternsEvalConfig | None


@dataclass(frozen=True)
class RunInstance:
    """A run's identity + logging lineage — the per-run bits that are NOT algorithm config.
    Minted/stamped by the launcher (`pd-lm`); a toy mints its own."""

    run_name: str
    """Human-readable display name (the wandb run NAME)."""
    run_id: str
    """Canonical `p-<8hex>` id (wandb run ID + run-dir name)."""
    out_dir: Path
    wandb: WandbConfig | None
    resume_provenance: ResumeProvenance | None
    """Set on a fine-tune run: the parent run dir + step to initialize V/U + ci_fn from
    (SPEC S33). `None` for a fresh-from-init run."""

    @property
    def run_dir(self) -> Path:
        return self.out_dir / self.run_id


@dataclass(frozen=True)
class BuiltRun:
    """Everything the generic engine needs for one decomposition run: the pydantic
    algorithm config (read DIRECTLY) plus the lab-built objects.

    `pd` / `runtime` / `cadence` are the verbatim pydantic config — the engine reads
    optimizers / loss metrics / faith warmup / seed / steps / cadence off them,
    so there is no flattened mirror to drift. The rest is what composition resolves: the
    run identity, the decomposed target (only `.sites` is read), the data source (`None`
    for a toy), the built CI-fn architecture, and the resolved scalar-tier eval config."""

    pd: PDConfig
    runtime: RuntimeConfig
    cadence: Cadence
    run: RunInstance
    target: TargetSites
    """The decomposed target config — only its `sites` are read by the generic engine. An
    LM target config (lab-side) or a lab toy target config (satisfying `TargetSites`)."""
    data: DataConfig | None
    """The LM parquet data source; `None` for a toy run (its synthetic data lives in the
    lab provider's `sample_batch`)."""
    ci_fn: CIFnArch
    eval: EvalConfig | None
